site_name: async_app
site_description: A simple framework to create async apps in Python.
site_author: jneines
site_url: https://jneines.github.io/async_app
repo_url: https://github.com/jneines/async_app

copyright: "Copyright &copy; 2024 - 2024 Jens Nie"

theme:
    palette:
        - scheme: default
          #   primary: blue
          #   accent: indigo
          toggle:
              icon: material/toggle-switch-off-outline
              name: Switch to dark mode
        - scheme: slate
          primary: indigo
          accent: indigo
          toggle:
              icon: material/toggle-switch
              name: Switch to light mode
    name: material
    icon:
        repo: fontawesome/brands/github
    # logo: assets/logo.png
    # favicon: assets/favicon.png
    features:
        - navigation.instant
        - navigation.tracking
        - navigation.top
        - search.highlight
        - search.share
    custom_dir: "docs/overrides"
    font:
        text: Google Sans
        code: Regular

plugins:
    - search
    - mkdocstrings
    - git-revision-date
    - git-revision-date-localized:
          enable_creation_date: true
          type: timeago
    # - pdf-export
    - mkdocs-jupyter:
          include_source: True
          ignore_h1_titles: True
          execute: True
          allow_errors: false
          ignore: ["conf.py"]
          execute_ignore: ["*ignore.ipynb"]
          
markdown_extensions:
    - admonition
    - abbr
    - attr_list
    - def_list
    - footnotes
    - meta
    - md_in_html
    - pymdownx.superfences
    - pymdownx.highlight:
          linenums: true
    - toc:
          permalink: true

# extra:
#     analytics:
#         provider: google
#         property: UA-XXXXXXXXX-X

nav:
    - Home: index.md
    - Installation: installation.md
    - Usage: usage.md
    - Contributing: contributing.md
    - FAQ: faq.md
    - Changelog: changelog.md
    - Report Issues: https://github.com/jneines/async_app/issues
      #- Examples:
      #  - examples/intro.ipynb
    - API Reference:
          - app module: async_app.md
          - app_factory module: app_factory.md
          - config module: config.md
          - logger module: logger.md
          - messenger module: messenger.md
          - patterns module: patterns.md
          - state module: state.md
          - tools module: tools.md
            #- common module: common.md
